name: Jupiter Variation
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.8707970548421144
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2eeeb'
    - '#98a8c2'
    - '#091933'
    - '#54647d'
    - '#313f59'
  brandStrength: 1
  lightness: 0.5006237651687115
  saturation: 1
  rhythmicContrast: 0.011391788488253951
purpose: []
