name: Jupiter Variation
favicon: null
layout_spectrum: 0.47558824601583183
typography_spectrum: 0.8707970548421144
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4488364087883383
  lightness: 0.5006237651687115
  saturation: 0.12811313103884459
  rhythmicContrast: 0.011391788488253951
purpose: []
