typography_spectrum: 0.1066051502712071
color:
  brandColors:
    - '#2E2E2E'
    - '#BABABA'
    - '#494949'
    - '#909090'
    - '#D5D5D5'
  brandStrength: 0.16609516041353345
  lightness: 0.6666366343852133
  saturation: 0.3120559202507138
  rhythmicContrast: 0.30492869415320456
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7485863149631768
analytics:
  google: UA-85368977-1
  facebook: null
  twitter: null
name: Jupiter Variation
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: A Music Blog...
content: []
purpose:
  - type: contact
    url: 'mailto:jupitervariations@gmail.com'
    label: Contact me
